### ISSUE TITLE
Please remove bash script from smoking.Rmd

### ISSUE THREAD

**Issue by audreyrenson** [audreyrenson/nychanes2microbiome#3]
In order to be able to build the vignette for the smoking analysis in Windows, it can't have bash code in it -- could you please find a work-around so bash code is not necessary?

**Comment by lwaldron** [comment]
You mean at the top, the `#biom` lines? If these are done as comments, they shouldn't affect the vignette building?  I think the work-around is that the required QIIME output is stored in the repository so that it doesn't have to be run again, but some additional documentation about how QIIME was run, version etc is called for.

**Comment by lwaldron** [comment]
This issue was moved to waldronlab/nychanesmicrobiome#3
